[env:pico]
platform = raspberrypi
board = pico
framework = arduino

; Ottimizzazioni per la massima velocità del processore
build_flags = 
    -O2
    -D CORE_DEBUG_LEVEL=0
    -D USER_SETUP_LOADED=1
    -D ST7735_DRIVER=1
    -D TFT_WIDTH=128
    -D TFT_HEIGHT=160
    -D SPI_FREQUENCY=40000000

; Librerie necessarie per il progetto
lib_deps =
    bodmer/TFT_eSPI@^2.5.31
    bodmer/TJpg_Decoder@^1.1.0
    adafruit/SdFat - Adafruit Fork@^2.2.1
